name: Build and Deploy

on: [push]

env:
  VITE_BACKEND_URL: https://sdp-sandbox-billing.cluster01.viind.io/graphql

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install and Test
        run: |
          npx pnpm install
          npx pnpm run test

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install and Build
        run: |
          npx pnpm install
          npx pnpm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: dist
          folder: dist
